# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_core/audio_preparer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc_core/audio_preparer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1egrpc_core/audio_preparer.proto\x12\x0e\x61udio_preparer\"*\n\x05\x41udio\x12\x13\n\x0bsample_rate\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x01\"4\n\rAudioResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03\x65rr\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t2\x96\x01\n\rAudioPreparer\x12\x42\n\nfind_audio\x12\x15.audio_preparer.Audio\x1a\x1d.audio_preparer.AudioResponse\x12\x41\n\tadd_audio\x12\x15.audio_preparer.Audio\x1a\x1d.audio_preparer.AudioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_core.audio_preparer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIO']._serialized_start=50
  _globals['_AUDIO']._serialized_end=92
  _globals['_AUDIORESPONSE']._serialized_start=94
  _globals['_AUDIORESPONSE']._serialized_end=146
  _globals['_AUDIOPREPARER']._serialized_start=149
  _globals['_AUDIOPREPARER']._serialized_end=299
# @@protoc_insertion_point(module_scope)
